Repository C2Devel/terraform-provider-rockitcloud, pull requests merged in 2024-11, with the labels that each got.

#55 add iam resources support
  internal/provider/provider.go
  internal/service/iam/consts.go
  internal/service/iam/find.go
  internal/service/iam/group.go
  internal/service/iam/group_data_source.go
  internal/service/iam/group_membership.go
  internal/service/iam/group_policy_attachment.go
  internal/service/iam/policy.go
  internal/service/iam/policy_data_source.go
  internal/service/iam/project.go
  internal/service/iam/project_data_source.go
  internal/service/iam/role_test.go
  internal/service/iam/tags.go
  internal/service/iam/user.go
  internal/service/iam/user_data_source.go
  internal/service/iam/user_group_membership.go
  internal/service/iam/user_policy_attachment.go
  internal/service/iam/users_data_source.go
  internal/verify/validate.go
  internal/verify/validate_test.go
  website/docs/d/iam_group.html.markdown
  website/docs/d/iam_policy.html.markdown
  website/docs/d/iam_project.html.markdown
  website/docs/d/iam_user.html.markdown
  website/docs/d/iam_users.html.markdown
  website/docs/r/iam_group.html.markdown
  website/docs/r/iam_group_membership.html.markdown
  website/docs/r/iam_group_policy_attachment.markdown
  website/docs/r/iam_policy.html.markdown
  website/docs/r/iam_project.html.markdown
  website/docs/r/iam_user.html.markdown
  website/docs/r/iam_user_group_membership.html.markdown
  website/docs/r/iam_user_policy_attachment.markdown
  website/docs/r/paas_service.html.markdown
  website_unsupported/d_unsupported/iam_group.html.markdown
  website_unsupported/d_unsupported/iam_policy.html.markdown
  website_unsupported/d_unsupported/iam_user.html.markdown
  website_unsupported/d_unsupported/iam_users.html.markdown
  website_unsupported/r_unsupported/iam_group.html.markdown
  website_unsupported/r_unsupported/iam_group_membership.html.markdown
  website_unsupported/r_unsupported/iam_group_policy_attachment.markdown
  website_unsupported/r_unsupported/iam_policy.html.markdown
  website_unsupported/r_unsupported/iam_user.html.markdown
  website_unsupported/r_unsupported/iam_user_group_membership.html.markdown
  website_unsupported/r_unsupported/iam_user_policy_attachment.markdown
Labels: enhancement

#52 update VPN connection types: add ipsec.legacy, remove ipsec.1-aes256
  internal/service/ec2/consts.go
  website/docs/r/customer_gateway.html.markdown
  website_unsupported/r_unsupported/vpn_connection.html.markdown
Labels: bug

#50 add acceptance test on PaaS ElasticSearch creation
  docs/c2/README.md
  internal/provider/provider.go
  internal/service/paas/service_test.go
  names/names_data.csv
Labels: need description

#61 paas: add name for service and instance endpoints
  internal/service/paas/service.go
  internal/service/paas/service_data_source.go
  internal/service/paas/service_test.go
  website/docs/d/paas_service.html.markdown
  website/docs/r/paas_service.html.markdown
Labels: bug

#63 config: replace username with project name in ARN account id
  internal/conns/config.go
Labels: bug
